name: Run Scripts

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug env
        run: |
          if [ -z "$SUPABASE_URL" ]; then echo "❌ SUPABASE_URL is empty"; else echo "✅ SUPABASE_URL is set"; fi
          if [ -z "$SUPABASE_KEY" ]; then echo "❌ SUPABASE_KEY is empty"; else echo "✅ SUPABASE_KEY is set"; fi

      - name: Run script.py
        run: python script.py

      - name: Run webScraping.py
        run: python webScraping.py
